version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler:2.2.5
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 83:35:36:55:59:61:1f:0d:2e:08:6b:d1:01:a1:01:37
      - run: pwd
      - run: ls ~/key
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/var/www/projects/rails-test/deploy.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master